<?xml version="1.0" encoding="UTF-8"?>
<!--
This file was generated by Altova MapForce 2014r2sp1

YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.

Refer to the Altova MapForce Documentation for further details.
http://www.altova.com/mapforce
-->
<xsl:stylesheet version="2.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:fn="http://www.w3.org/2005/xpath-functions" xmlns:ns0="urn:switchyard-quickstart:transform-xslt:1.0" exclude-result-prefixes="xs fn ns0">
	<xsl:output method="xml" encoding="UTF-8" byte-order-mark="no" indent="yes"/>
	<xsl:template match="/">
		<xsl:variable name="var1_order" as="node()?" select="ns0:order"/>
		<orderAck xmlns="urn:switchyard-quickstart:transform-xslt:1.0">
			<xsl:attribute name="xsi:schemaLocation" namespace="http://www.w3.org/2001/XMLSchema-instance" />
			<xsl:for-each select="$var1_order">
				<orderId xmlns="">
					<xsl:sequence select="fn:string(orderId)"/>
				</orderId>
			</xsl:for-each>
			<xsl:for-each select="$var1_order">
				<accepted xmlns="">
					<xsl:sequence select="xs:string((fn:string(itemId) = 'BUTTER'))"/>
				</accepted>
			</xsl:for-each>
			<xsl:for-each select="$var1_order">
				<status xmlns="">
					<xsl:choose>
						<xsl:when test="(xs:integer(fn:string(quantity)) &lt;= xs:decimal('200'))">
							<xsl:sequence select="'Order Accepted'"/>
						</xsl:when>
						<xsl:otherwise>
							<xsl:sequence select="'Not Enough Stock'"/>
						</xsl:otherwise>
					</xsl:choose>
				</status>
			</xsl:for-each>
		</orderAck>
	</xsl:template>
</xsl:stylesheet>
