<?xml version="1.0" encoding="UTF-8"?>
<!--
This file was generated by Altova MapForce 2014r2sp1

YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.

Refer to the Altova MapForce Documentation for further details.
http://www.altova.com/mapforce
-->
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:agt="http://www.altova.com/Mapforce/agt" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:ns0="urn:switchyard-quickstart:transform-xslt:1.0" exclude-result-prefixes="agt xs ns0">
	<xsl:output method="xml" encoding="UTF-8" indent="yes"/>
	<xsl:template name="agt:MapToorderAck_var2_create_orderId">
		<xsl:param name="var1_current"/>
		<orderId>
			<xsl:value-of select="string($var1_current/orderId)"/>
		</orderId>
	</xsl:template>
	<xsl:template name="agt:MapToorderAck_var4_create_accepted">
		<xsl:param name="var3_current"/>
		<accepted>
			<xsl:value-of select="string((string($var3_current/itemId) = 'BUTTER'))"/>
		</accepted>
	</xsl:template>
	<xsl:template name="agt:MapToorderAck_var6_create_status">
		<xsl:param name="var5_current"/>
		<status>
			<xsl:choose>
				<xsl:when test="string((floor(number(string($var5_current/quantity))) &lt;= '200')) != 'false'">
					<xsl:value-of select="'Order Accepted'"/>
				</xsl:when>
				<xsl:otherwise>
					<xsl:value-of select="'Not Enough Stock'"/>
				</xsl:otherwise>
			</xsl:choose>
		</status>
	</xsl:template>
	<xsl:template match="/">
		<orderAck xmlns="urn:switchyard-quickstart:transform-xslt:1.0">
<!--			
			<xsl:attribute name="xsi:schemaLocation" namespace="http://www.w3.org/2001/XMLSchema-instance">urn:switchyard-quickstart:transform-xslt:1.0 C:/DOCUME~1/nandan/MYDOCU~1/RHT/orderAck.xsd</xsl:attribute> 
-->
			<xsl:for-each select="ns0:order">
				<xsl:call-template name="agt:MapToorderAck_var2_create_orderId">
					<xsl:with-param name="var1_current" select="."/>
				</xsl:call-template>
			</xsl:for-each>
			<xsl:for-each select="ns0:order">
				<xsl:call-template name="agt:MapToorderAck_var4_create_accepted">
					<xsl:with-param name="var3_current" select="."/>
				</xsl:call-template>
			</xsl:for-each>
			<xsl:for-each select="ns0:order">
				<xsl:call-template name="agt:MapToorderAck_var6_create_status">
					<xsl:with-param name="var5_current" select="."/>
				</xsl:call-template>
			</xsl:for-each>
		</orderAck>
	</xsl:template>
</xsl:stylesheet>
